# Generated by Django 5.2.1 on 2025-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Data/default.jpg', null=True, upload_to='Data/profile_picture'),
        ),
    ]
